// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaliffbpblaxjeukreda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbGlmZmJwYmxheGpldWtyZWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTYyMjksImV4cCI6MjA2MDI3MjIyOX0.UtagCQmAdki78fj8zhBPbARwcXC1ZFIuKJgwvmXJwZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);